# This workflow will install Python dependencies and run the script

name: run

on:
  workflow_dispatch: # add run button in github

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; fi
    - name: Send mail
      if: failure()
      uses: wadeww/send-email-action@master
      with:
        server_address: ${{SECRETS.EMAIL_SERVER}}
        port: ${{secrets.EMAIL_PORT}}
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: "FAILED: ${{github.repository}} run job"
        body: GitHub Actions run job for ${{github.repository}} failed!
        to: ${{secrets.EMAIL_LIST}}
        from: ${{secrets.EMAIL_FROM}}
